/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum19062025;

/**
 *
 * @author nofri
 */
public class Makanan extends javax.swing.JFrame {

    private MenuUtama utama;
    
    public Makanan() {
        initComponents();
    }
    public Makanan(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkMieRebus = new javax.swing.JCheckBox();
        chkMieAyam = new javax.swing.JCheckBox();
        chkNasGor = new javax.swing.JCheckBox();
        chkBakso = new javax.swing.JCheckBox();
        txtMieRebus = new javax.swing.JTextField();
        txtMieAyam = new javax.swing.JTextField();
        txtNasGor = new javax.swing.JTextField();
        txtBakso = new javax.swing.JTextField();
        cbMieRebus = new javax.swing.JComboBox<>();
        cbMieAyam = new javax.swing.JComboBox<>();
        cbNasGor = new javax.swing.JComboBox<>();
        cbBakso = new javax.swing.JComboBox<>();
        txtTotMieRebus = new javax.swing.JTextField();
        txtTotMieAyam = new javax.swing.JTextField();
        txtTotNasGor = new javax.swing.JTextField();
        txtTotBakso = new javax.swing.JTextField();
        btnTotHarga = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtTotMakanan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DAFTAR MENU MAKANAN");

        chkMieRebus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chkMieRebus.setText("Mie Rebus");
        chkMieRebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieRebusActionPerformed(evt);
            }
        });

        chkMieAyam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chkMieAyam.setText("Mie Ayam");
        chkMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieAyamActionPerformed(evt);
            }
        });

        chkNasGor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chkNasGor.setText("Nasi Goreng");
        chkNasGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasGorActionPerformed(evt);
            }
        });

        chkBakso.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chkBakso.setText("Bakso");
        chkBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBaksoActionPerformed(evt);
            }
        });

        txtMieRebus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMieRebus.setText("0");

        txtMieAyam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMieAyam.setText("0");

        txtNasGor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtNasGor.setText("0");

        txtBakso.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtBakso.setText("0");

        cbMieRebus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbMieRebus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMieRebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieRebusActionPerformed(evt);
            }
        });

        cbMieAyam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbMieAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieAyamActionPerformed(evt);
            }
        });

        cbNasGor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbNasGor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasGorActionPerformed(evt);
            }
        });

        cbBakso.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbBakso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaksoActionPerformed(evt);
            }
        });

        txtTotMieRebus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotMieRebus.setText("0");

        txtTotMieAyam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotMieAyam.setText("0");

        txtTotNasGor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotNasGor.setText("0");

        txtTotBakso.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotBakso.setText("0");

        btnTotHarga.setBackground(new java.awt.Color(102, 204, 0));
        btnTotHarga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTotHarga.setText("Total Harga");
        btnTotHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotHargaActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 204, 0));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 204, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnBack.setText("Kembali Ke Menu Utama");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtTotMakanan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotMakanan.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(236, 236, 236))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(chkMieRebus)
                                .addGap(54, 54, 54)
                                .addComponent(txtMieRebus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMieAyam)
                                    .addComponent(chkBakso)
                                    .addComponent(chkNasGor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNasGor)
                                    .addComponent(txtMieAyam)
                                    .addComponent(txtBakso, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMieRebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotHarga))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotMieRebus)
                            .addComponent(txtTotMieAyam)
                            .addComponent(txtTotNasGor)
                            .addComponent(txtTotBakso)
                            .addComponent(txtTotMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMieRebus)
                    .addComponent(txtMieRebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMieRebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMieRebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMieAyam)
                    .addComponent(txtMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasGor)
                    .addComponent(txtNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotNasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBakso)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotHarga)
                    .addComponent(txtTotMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnReset))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieAyamActionPerformed
        txtMieAyam.setText("15000");
    }//GEN-LAST:event_chkMieAyamActionPerformed

    private void chkMieRebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieRebusActionPerformed
        txtMieRebus.setText("12000");
    }//GEN-LAST:event_chkMieRebusActionPerformed

    private void chkNasGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasGorActionPerformed
        txtNasGor.setText("13000");
    }//GEN-LAST:event_chkNasGorActionPerformed

    private void chkBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBaksoActionPerformed
        txtBakso.setText("20000");
    }//GEN-LAST:event_chkBaksoActionPerformed

    private void cbMieRebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieRebusActionPerformed
        int jml = (int)cbMieRebus.getSelectedIndex();
        double harga = Double.parseDouble(txtMieRebus.getText());
        double total = jml*harga;
        txtTotMieRebus.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieRebusActionPerformed

    private void cbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieAyamActionPerformed
        int jml = (int)cbMieAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtMieAyam.getText());
        double total = jml*harga;
        txtTotMieAyam.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieAyamActionPerformed

    private void cbNasGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasGorActionPerformed
        int jml = (int)cbNasGor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasGor.getText());
        double total = jml*harga;
        txtTotNasGor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasGorActionPerformed

    private void cbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBaksoActionPerformed
        int jml = (int)cbBakso.getSelectedIndex();
        double harga = Double.parseDouble(txtBakso.getText());
        double total = jml*harga;
        txtTotBakso.setText(Double.toString(total));
    }//GEN-LAST:event_cbBaksoActionPerformed

    private void btnTotHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotHargaActionPerformed
        double mieRebus = Double.parseDouble(txtTotMieRebus.getText());
        double mieAyam = Double.parseDouble(txtTotMieAyam.getText());
        double NasGor = Double.parseDouble(txtTotNasGor.getText());
        double Bakso = Double.parseDouble(txtTotBakso.getText());
        double total = mieRebus+mieAyam+NasGor+Bakso;
        txtTotMakanan.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotHargaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNasGor.setText("0");
        txtMieRebus.setText("0");
        txtMieAyam.setText("0");
        txtBakso.setText("0");
        txtTotMakanan.setText("0");
        cbNasGor.setSelectedIndex(0);
        cbMieRebus.setSelectedIndex(0);
        cbMieAyam.setSelectedIndex(0);
        cbBakso.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String total = txtTotMakanan.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotHarga;
    private javax.swing.JComboBox<String> cbBakso;
    private javax.swing.JComboBox<String> cbMieAyam;
    private javax.swing.JComboBox<String> cbMieRebus;
    private javax.swing.JComboBox<String> cbNasGor;
    private javax.swing.JCheckBox chkBakso;
    private javax.swing.JCheckBox chkMieAyam;
    private javax.swing.JCheckBox chkMieRebus;
    private javax.swing.JCheckBox chkNasGor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBakso;
    private javax.swing.JTextField txtMieAyam;
    private javax.swing.JTextField txtMieRebus;
    private javax.swing.JTextField txtNasGor;
    private javax.swing.JTextField txtTotBakso;
    private javax.swing.JTextField txtTotMakanan;
    private javax.swing.JTextField txtTotMieAyam;
    private javax.swing.JTextField txtTotMieRebus;
    private javax.swing.JTextField txtTotNasGor;
    // End of variables declaration//GEN-END:variables
}
